### ISSUE TITLE
Main hier weglaten?

### ISSUE THREAD

**Issue by joostf** [MohamadAlGhorani/blok-web#5]
https://github.com/MohamadAlGhorani/blok-web/blob/6c95e110a4bbee07e6654f1607ab3607b97ea9d7/index.html#L43

Je bundelt verschillende sections in de main, terwijl alleen de belangrijkste content in de main zou moeten staan

**Comment by MohamadAlGhorani** [comment]
ik heb de main helemaal weg gedaan.
